- name: condition
  hosts: all
  tasks:
  - name: print centos
    debug: 
      msg: "this is centos"
    when: ansible_distribution=="centos"
  - name: print ubuntu
    debug: 
      msg: "this is ubuntu"
    when: ansible_distribution=="ubuntu"
    