- name: condition
  hosts: all
  tasks:
  - name: centos
    debug:
      msg: "this is centos"
    when: ansible_distribution == "centos"
  - name: ubuntu
    debug:
     msg: "this is ubuntu"
    when: ansible_distribution == "cubuntu"