- name: my web server
  hosts: all
  tasks:
  - name: install httpd
    apt:
     name:  httpd
     state: latest
  - name: start httpd
    systemd:
      name: httpd
      state: restarted
      enable: true
  - name: deployment
    copy: 
     src: ./index.html
     dest: /var/www/html/index.html