- name: root privilage
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      update_cache: yes
      state: latest
    when: ansible_os_family == "Redhat"
  - name: install apache2
    apt:
     name: apache2
     update_cache: yes
     state: latest
    when: ansible_os_family == "Debian"